version: '3'

services:
  app:
    build: .
    container_name: swapi-app
    restart: always
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    links:
      - db
    networks:
      - dev
    depends_on:
      - db

  db:
    image: mongo
    container_name: swapi-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always
    ports:
      - "27017:27017"
    # volumes:
    #   - .docker/mongodb:/data/db
    networks:
      - dev

  redis:
    image: redis
    container_name: swapi-redis
    networks:
      - dev
    volumes:
      - .docker/redis:/data/db
    depends_on:
      - db
    ports:
      - "6379:6379"

networks:
    dev:
      driver: bridge
