version: '3'

services:
    # redis:
    #   image: redis:alpine
    #   command: redis-server --requirepass Redis2019!
    #   ports:
    #     - "16379:6379"
    #   networks:
    #     - databases

#   mongo-express:
#     image: mongo-express
#     ports:
#       - 19081:8081
#     environment:
#       ME_CONFIG_BASICAUTH_USERNAME: glaubergoncalves
#       ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
#       ME_CONFIG_MONGODB_PORT: 27017
#       ME_CONFIG_MONGODB_ADMINUSERNAME: root
#       ME_CONFIG_MONGODB_ADMINPASSWORD: apisw
#     links:
#       - mongo
#     networks:
#       - dev

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    # volumes:
    #   - ./.docker/mongodb:/data/db
    networks:
      - dev      

networks: 
    dev:
      driver: bridge